name: push-datasets
on: push

jobs:
  push-dataset: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Upload datasets to s3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
            aws_key_id: ${{secrets.AWS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_bucket: chemmatdata
            source_dir: datasets 