name: push-datasets
on: push

jobs:
  push-dataset: 
    runs-on: ubuntu-latest
    steps:
      - name: Upload materials.json to s3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
            aws_key_id: ${{secrets.AWS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_bucket: chemmatdata
            source_dir: materials.json

      - name: Upload molecules.json to s3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
            aws_key_id: ${{secrets.AWS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_bucket: chemmatdata
            source_dir: molecules.json